# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 11230

# Define environment variable
ENV FLASK_RUN_PORT 11230
ENV MODE standalone
ENV CART_SERVICE_URL 'http://studentdocker.informatika.uni-mb.si:11234/'
ENV LOG_SERVICE_URL 'http://studentdocker.informatika.uni-mb.si:11235/'
ENV PRODUCT_SERVICE_URL 'http://studentdocker.informatika.uni-mb.si:11233/'
ENV USER_SERVICE_URL 'http://studentdocker.informatika.uni-mb.si:11231/'

# Run app.py when the container launches
CMD ["python", "index.py"]