# Specify the version number
version: '3'
services:
  cart-service:
    # The database corresponds to the Dockerfile directory
    image: ferisoa/projekt:cart-service1
    # Restart method: always
    restart: always
    # Port Mapping
    ports:
      - 11234:11234
    # container name
    container_name: cart-service
    # hostname
    hostname: cart-service
    # Environment variable, set the startup mode to stand-alone startup
    environment:
      PORT: 11234
      PRODUCT_SERVICE_URL: 'http://product-service:11233'
      USER_SERVICE_URL: 'http://user-service:11231'
      DB_PROD: 'mongodb://cart-db:27017/'
      DB: 'mongodb+srv://test:dy2nSenFodHf5V3V@cluster0.kfl4t.mongodb.net/cart-service?retryWrites=true&w=majority'
      NODE_ENV: 'production'
      RABBITMQ_URL_DEV: 'amqp://guest:guest@164.8.222.89:5672'
      RABBITMQ_URL: 'amqp://student:student123@rabbit:5672'
    # add to web app
    networks:
      - app
      - rabbit
    depends_on:
      - cart-db
  cart-db:
    container_name: cart-db
    hostname: cart-db
    networks:
      - app
      - rabbit
    image: mongo
    expose:
      - "27017"
#    volumes:
#      - ./services/cart/db:/data/db
  log-service:
    image: ferisoa/projekt:log-service1
    restart: always
    ports:
      - 11235:11235
    container_name: log-service
    hostname: log-service
    environment:
      PORT: 11235
      SECRET: 'secret'
      PRODUCT_SERVICE_URL: 'http://product-service:11233'
      STATS_URL: 'https://soa051323jdsf2.azurewebsites.net/'
      DB_PROD: 'mongodb://log-db:27017/'
      DB: 'mongodb+srv://test:dy2nSenFodHf5V3V@cluster0.kfl4t.mongodb.net/log-service?retryWrites=true&w=majority'
      NODE_ENV: 'production'
      RABBITMQ_URL_DEV: 'amqp://guest:guest@164.8.222.89:5672'
      RABBITMQ_URL: 'amqp://student:student123@rabbit:5672'
    networks:
      - app
      - rabbit
    depends_on:
      - log-db
  log-db:
    container_name: log-db
    hostname: log-db
    networks:
      - app
      - rabbit
    expose:
      - "27017"
    image: mongo
#    volumes:
#      - ./services/log/db:/data/db
  product-service:
    image: ferisoa/projekt:product-service2
    restart: always
    ports:
      - 11233:11233
    container_name: product-service
    hostname: product-service
    environment:
      NODE_ENV: 'production'
      RABBITMQ_URL_DEV: 'amqp://guest:guest@164.8.222.89:5672'
      RABBITMQ_URL: 'amqp://student:student123@rabbit:5672'
      PORT: 11233
      USER_SERVICE_URL: 'http://user-service:11231'
      DB_PROD: 'mongodb://product-db:27017/'
      DB: 'mongodb+srv://test:dy2nSenFodHf5V3V@cluster0.kfl4t.mongodb.net/product-service?retryWrites=true&w=majority'
      DB_LOG: 'mongodb://log-db:27017/'
    networks:
      - app
      - rabbit
    depends_on:
      - product-db
  product-db:
    container_name: product-db
    hostname: product-db
    expose:
      - "27017"
    networks:
      - app
      - rabbit
    image: mongo
#    volumes:
#      - ./services/product/db:/data/db
  user-service:
    image: ferisoa/projekt:user-service3
    restart: always
    ports:
      - 11231:11231
    container_name: user-service
    hostname: user-service
    environment:
      NODE_ENV: 'production'
      RABBITMQ_URL_DEV: 'amqp://guest:guest@164.8.222.89:5672'
      RABBITMQ_URL: 'amqp://student:student123@rabbit:5672'
      PORT: 11231
      SECRET: 'secret'
      PRODUCT_SERVICE_URL: 'http://user-service:11233'
      DB_PROD: 'mongodb://user-db:27017/'
      DB: 'mongodb+srv://test:dy2nSenFodHf5V3V@cluster0.kfl4t.mongodb.net/user-service?retryWrites=true&w=majority'
    networks:
      - app
      - rabbit
    depends_on:
      - user-db
  user-db:
    container_name: user-db
    hostname: user-db
    expose:
      - "27017"
    networks:
      - app
      - rabbit
    image: mongo
#    volumes:
#      - ./services/user/db:/data/db
  api-gateway:
    image: ferisoa/projekt:api-gateway-c
    restart: always
    ports:
      - 11230:11230
    container_name: api-gateway
    hostname: api-gateway
    environment:
      FLASK_RUN_PORT: 11230
      MODE: standalone
      CART_SERVICE_URL: 'http://cart-service:11234/'
      LOG_SERVICE_URL: 'http://log-service:11235/'
      PRODUCT_SERVICE_URL: 'http://product-service:11233/'
      USER_SERVICE_URL: 'http://user-service:11231/'
    networks:
      - app
      - rabbit
  web-app:
    image: ferisoa/projekt:web-app
    restart: always
    ports:
      - 11237:11237
    container_name: web-app
    hostname: web-app
    environment:
      PORT: 11237
      NODE_ENV: 'production'
      CART_SERVICE_URL: 'http://studentdocker.informatika.uni-mb.si:11230/cart'
      LOG_SERVICE_URL: 'http://studentdocker.informatika.uni-mb.si:11230/logs'
      PRODUCT_SERVICE_URL: 'http://studentdocker.informatika.uni-mb.si:11230/product'
      USER_SERVICE_URL: 'http://studentdocker.informatika.uni-mb.si:11230/user'
      STATS_SERVICE_URL: 'http://soa051323jdsf2.azurewebsites.net/'
    networks:
      - app
      - rabbit

# set network as app
networks:
  rabbit:
    name: rabbit_network
    external: true
  app:

volumes:
  user-db-data:
  product-db-data:
  cart-db-data:
  log-db-data: