# Use the official lightweight Node.js 14 image.
# https://hub.docker.com/_/node
FROM node:14-slim

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN npm install --only=production

# Copy local code to the container image.
COPY . .

RUN npm run build

ENV PORT=11234
ENV PRODUCT_SERVICE_URL='http://studentdocker.informatika.uni-mb.si:11233/'
ENV USER_SERVICE_URL='http://studentdocker.informatika.uni-mb.si:11231/'
ENV DB_PROD='mongodb://cart-db:27017/'
ENV DB='mongodb+srv://test:dy2nSenFodHf5V3V@cluster0.kfl4t.mongodb.net/cart-service?retryWrites=true&w=majority'
ENV NODE_ENV='production'
ENV RABBITMQ_URL_DEV='amqp://guest:guest@164.8.222.89:5672'
ENV RABBITMQ_URL='amqp://student:student123@rabbit:5672'


EXPOSE 11234

# Run the web service on container startup.
CMD [ "npm", "start" ]